FROM php:7.3-fpm

RUN apt-get update && apt-get install -y
RUN apt-get -y install openssl \
    php7.3-mysql \
    php7.3-common \
    php7.3-curl \
    php7.3-json \
    php7.3-mbstring \
    php7.3-mysql \
    php7.3-xml \
    php7.3-zip \
    php7.3-gd  
